### ISSUE TITLE
Problem with GAMA Spatial Operator

### ISSUE THREAD

**Issue by agrignard** [CityScope/CSL_Paris#11]
This is more a GAMA bug that maybe @ptaillandier wants to track to it.

I sometimes have an error (which is not always appearing). I put it here just in case it's something that can be fixed at the GAMA level. Not a big deal for this specific project as the exhibition is (well was..) running on a stable 1.8 version

So here is the error that sometimes appears at the init (should I post it on the GAMA Github knowing that it's very specific to this project?)

`````
2 occurrences in 2 agents at cycle 0: Java error: nil value detected
in target <- closest_points_with(r,target_place)[0];
NullPointerException: null
msi.gaml.operators.Spatial$Punctal.closest_points_with(Spatial.java:4155)
gaml.additions.GamlAdditions.lambda$362(GamlAdditions.java:419)
msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:77)
msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:75)
msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
msi.gaml.statements.SetStatement.privateExecuteIn(SetStatement.java:150)
when applying the closest_points_with operator on nil and park(61)
in target <- closest_points_with(r,target_place)[0];
in else  {
	to_park <- true;
	if currentSimuState = 0  {
		bool same_zone <- false;
		loop while: same_zone = false  {
			target_place <- proba_choose_park.keys[rnd_choice(proba_choose_park.values)];
			same_zone <- park(target_place).zone = zone;
		}
	
	}else  {
		target_place <- proba_choose_park.keys[rnd_choice(proba_choose_park.values)];
	}
	

	road r <- closest_to(park(target_place).closest_roads,target_place);
	target <- closest_points_with(r,target_place)[0];
}

in if flip(proba_culture)  {
	if currentSimuState = 0  {
		bool same_zone <- false;
		loop while: same_zone = false  {
			target_place <- proba_choose_culture.keys[rnd_choice(proba_choose_culture.values)];
			same_zone <- culture(target_place).zone = zone;
		}
	
	}else  {
		target_place <- proba_choose_culture.keys[rnd_choice(proba_choose_culture.values)];
	}
	

	to_culture <- true;
	target <- culture(target_place).arrival_position[currentSimuState];
}else  {
	to_park <- true;
	if currentSimuState = 0  {
		bool same_zone <- false;
		loop while: same_zone = false  {
			target_place <- proba_choose_park.keys[rnd_choice(proba_choose_park.values)];
			same_zone <- park(target_place).zone = zone;
		}
	
	}else  {
		target_place <- proba_choose_park.keys[rnd_choice(proba_choose_park.values)];
	}
	

	road r <- closest_to(park(target_place).closest_roads,target_place);
	target <- closest_points_with(r,target_place)[0];
}


in else  {
	if flip(proba_culture)  {
		if currentSimuState = 0  {
			bool same_zone <- false;
			loop while: same_zone = false  {
				target_place <- proba_choose_culture.keys[rnd_choice(proba_choose_culture.values)];
				same_zone <- culture(target_place).zone = zone;
			}
		
		}else  {
			target_place <- proba_choose_culture.keys[rnd_choice(proba_choose_culture.values)];
		}
		
	
		to_culture <- true;
		target <- culture(target_place).arrival_position[currentSimuState];
	}else  {
		to_park <- true;
		if currentSimuState = 0  {
			bool same_zone <- false;
			loop while: same_zone = false  {
				target_place <- proba_choose_park.keys[rnd_choice(proba_choose_park.values)];
				same_zone <- park(target_place).zone = zone;
			}
		
		}else  {
			target_place <- proba_choose_park.keys[rnd_choice(proba_choose_park.values)];
		}
		
	
		road r <- closest_to(park(target_place).closest_roads,target_place);
		target <- closest_points_with(r,target_place)[0];
	}
	

}

in if flip(proba_wandering)  {
	road 
	if !active_zoning[currentSimuState]  {
		r <- one_of(people_graph[currentSimuState].edges);
	}else  {
		r <- one_of(people_graph[currentSimuState].edges where (road(each).zone = self.zone));
	}
	

	target <- any_location_in(r);
	target <- first(road(one_of(people_graph[currentSimuState].edges)).shape.points);
	wandering <- true;
	speed_walk_current <- speed_walk_current / 3.0;
}else  {
	if flip(proba_culture)  {
		if currentSimuState = 0  {
			bool same_zone <- false;
			loop while: same_zone = false  {
				target_place <- proba_choose_culture.keys[rnd_choice(proba_choose_culture.values)];
				same_zone <- culture(target_place).zone = zone;
			}
		
		}else  {
			target_place <- proba_choose_culture.keys[rnd_choice(proba_choose_culture.values)];
		}
		
	
		to_culture <- true;
		target <- culture(target_place).arrival_position[currentSimuState];
	}else  {
		to_park <- true;
		if currentSimuState = 0  {
			bool same_zone <- false;
			loop while: same_zone = false  {
				target_place <- proba_choose_park.keys[rnd_choice(proba_choose_park.values)];
				same_zone <- park(target_place).zone = zone;
			}
		
		}else  {
			target_place <- proba_choose_park.keys[rnd_choice(proba_choose_park.values)];
		}
		
	
		road r <- closest_to(park(target_place).closest_roads,target_place);
		target <- closest_points_with(r,target_place)[0];
	}
	

}


in else  {
	if flip(proba_wandering)  {
		road 
		if !active_zoning[currentSimuState]  {
			r <- one_of(people_graph[currentSimuState].edges);
		}else  {
			r <- one_of(people_graph[currentSimuState].edges where (road(each).zone = self.zone));
		}
		
	
		target <- any_location_in(r);
		target <- first(road(one_of(people_graph[currentSimuState].edges)).shape.points);
		wandering <- true;
		speed_walk_current <- speed_walk_current / 3.0;
	}else  {
		if flip(proba_culture)  {
			if currentSimuState = 0  {
				bool same_zone <- false;
				loop while: same_zone = false  {
					target_place <- proba_choose_culture.keys[rnd_choice(proba_choose_culture.values)];
					same_zone <- culture(target_place).zone = zone;
				}
			
			}else  {
				target_place <- proba_choose_culture.keys[rnd_choice(proba_choose_culture.values)];
			}
			
		
			to_culture <- true;
			target <- culture(target_place).arrival_position[currentSimuState];
		}else  {
			to_park <- true;
			if currentSimuState = 0  {
				bool same_zone <- false;
				loop while: same_zone = false  {
					target_place <- proba_choose_park.keys[rnd_choice(proba_choose_park.values)];
					same_zone <- park(target_place).zone = zone;
				}
			
			}else  {
				target_place <- proba_choose_park.keys[rnd_choice(proba_choose_park.values)];
			}
			
		
			road r <- closest_to(park(target_place).closest_roads,target_place);
			target <- closest_points_with(r,target_place)[0];
		}
		
	
	}
	

}

in if flip(proba_sortie)  {
	if active_zoning[currentSimuState]  {
		target_place <- closest_to(station where ((each.type = 'metro') and (each.zone = zone)),self);
		target <- closest_to(station where ((each.type = 'metro') and (each.zone = zone)),self).location;
	}else  {
		target_place <- closest_to(station where (each.type = 'metro'),self);
		target <- closest_to(station where (each.type = 'metro'),self).location;
	}
	

	target <- station(target_place).arrival_position[currentSimuState];
	to_exit <- true;
}else  {
	if flip(proba_wandering)  {
		road 
		if !active_zoning[currentSimuState]  {
			r <- one_of(people_graph[currentSimuState].edges);
		}else  {
			r <- one_of(people_graph[currentSimuState].edges where (road(each).zone = self.zone));
		}
		
	
		target <- any_location_in(r);
		target <- first(road(one_of(people_graph[currentSimuState].edges)).shape.points);
		wandering <- true;
		speed_walk_current <- speed_walk_current / 3.0;
	}else  {
		if flip(proba_culture)  {
			if currentSimuState = 0  {
				bool same_zone <- false;
				loop while: same_zone = false  {
					target_place <- proba_choose_culture.keys[rnd_choice(proba_choose_culture.values)];
					same_zone <- culture(target_place).zone = zone;
				}
			
			}else  {
				target_place <- proba_choose_culture.keys[rnd_choice(proba_choose_culture.values)];
			}
			
		
			to_culture <- true;
			target <- culture(target_place).arrival_position[currentSimuState];
		}else  {
			to_park <- true;
			if currentSimuState = 0  {
				bool same_zone <- false;
				loop while: same_zone = false  {
					target_place <- proba_choose_park.keys[rnd_choice(proba_choose_park.values)];
					same_zone <- park(target_place).zone = zone;
				}
			
			}else  {
				target_place <- proba_choose_park.keys[rnd_choice(proba_choose_park.values)];
			}
			
		
			road r <- closest_to(park(target_place).closest_roads,target_place);
			target <- closest_points_with(r,target_place)[0];
		}
		
	
	}
	

}


in enter  {
	do reinit_path ;
	target <- nil;
	walking <- true;
	wandering <- false;
	to_culture <- false;
	float speed_walk_current <- speed_walk;
	if flip(proba_sortie)  {
		if active_zoning[currentSimuState]  {
			target_place <- closest_to(station where ((each.type = 'metro') and (each.zone = zone)),self);
			target <- closest_to(station where ((each.type = 'metro') and (each.zone = zone)),self).location;
		}else  {
			target_place <- closest_to(station where (each.type = 'metro'),self);
			target <- closest_to(station where (each.type = 'metro'),self).location;
		}
		
	
		target <- station(target_place).arrival_position[currentSimuState];
		to_exit <- true;
	}else  {
		if flip(proba_wandering)  {
			road 
			if !active_zoning[currentSimuState]  {
				r <- one_of(people_graph[currentSimuState].edges);
			}else  {
				r <- one_of(people_graph[currentSimuState].edges where (road(each).zone = self.zone));
			}
			
		
			target <- any_location_in(r);
			target <- first(road(one_of(people_graph[currentSimuState].edges)).shape.points);
			wandering <- true;
			speed_walk_current <- speed_walk_current / 3.0;
		}else  {
			if flip(proba_culture)  {
				if currentSimuState = 0  {
					bool same_zone <- false;
					loop while: same_zone = false  {
						target_place <- proba_choose_culture.keys[rnd_choice(proba_choose_culture.values)];
						same_zone <- culture(target_place).zone = zone;
					}
				
				}else  {
					target_place <- proba_choose_culture.keys[rnd_choice(proba_choose_culture.values)];
				}
				
			
				to_culture <- true;
				target <- culture(target_place).arrival_position[currentSimuState];
			}else  {
				to_park <- true;
				if currentSimuState = 0  {
					bool same_zone <- false;
					loop while: same_zone = false  {
						target_place <- proba_choose_park.keys[rnd_choice(proba_choose_park.values)];
						same_zone <- park(target_place).zone = zone;
					}
				
				}else  {
					target_place <- proba_choose_park.keys[rnd_choice(proba_choose_park.values)];
				}
				
			
				road r <- closest_to(park(target_place).closest_roads,target_place);
				target <- closest_points_with(r,target_place)[0];
			}
			
		
		}
		
	
	}
	

}

in state walk_to_objective initial: true  {
	enter  {
		do reinit_path ;
		target <- nil;
		walking <- true;
		wandering <- false;
		to_culture <- false;
		float speed_walk_current <- speed_walk;
		if flip(proba_sortie)  {
			if active_zoning[currentSimuState]  {
				target_place <- closest_to(station where ((each.type = 'metro') and (each.zone = zone)),self);
				target <- closest_to(station where ((each.type = 'metro') and (each.zone = zone)),self).location;
			}else  {
				target_place <- closest_to(station where (each.type = 'metro'),self);
				target <- closest_to(station where (each.type = 'metro'),self).location;
			}
			
		
			target <- station(target_place).arrival_position[currentSimuState];
			to_exit <- true;
		}else  {
			if flip(proba_wandering)  {
				road 
				if !active_zoning[currentSimuState]  {
					r <- one_of(people_graph[currentSimuState].edges);
				}else  {
					r <- one_of(people_graph[currentSimuState].edges where (road(each).zone = self.zone));
				}
				
			
				target <- any_location_in(r);
				target <- first(road(one_of(people_graph[currentSimuState].edges)).shape.points);
				wandering <- true;
				speed_walk_current <- speed_walk_current / 3.0;
			}else  {
				if flip(proba_culture)  {
					if currentSimuState = 0  {
						bool same_zone <- false;
						loop while: same_zone = false  {
							target_place <- proba_choose_culture.keys[rnd_choice(proba_choose_culture.values)];
							same_zone <- culture(target_place).zone = zone;
						}
					
					}else  {
						target_place <- proba_choose_culture.keys[rnd_choice(proba_choose_culture.values)];
					}
					
				
					to_culture <- true;
					target <- culture(target_place).arrival_position[currentSimuState];
				}else  {
					to_park <- true;
					if currentSimuState = 0  {
						bool same_zone <- false;
						loop while: same_zone = false  {
							target_place <- proba_choose_park.keys[rnd_choice(proba_choose_park.values)];
							same_zone <- park(target_place).zone = zone;
						}
					
					}else  {
						target_place <- proba_choose_park.keys[rnd_choice(proba_choose_park.values)];
					}
					
				
					road r <- closest_to(park(target_place).closest_roads,target_place);
					target <- closest_points_with(r,target_place)[0];
				}
				
			
			}
			
		
		}
		
	
	}

	road r <- road(copy(current_edge));
	if r != nil  {
		blocked <- false;
		int gr <- r.tl_group;
		if float(gr) != 0  {
			point p1 <- ((destination - location) / norm(destination - location)) * 10;
			int r_id <- 0;
			list<road> lr <- ped_blocking_roads[currentSimuState][r.tl_group][phase_per_group[r.tl_group] - 1];
			loop while: !blocked and (r_id < length(lr))  {
				if intersects(polyline([location + current_offset,(location + current_offset) + p1]),lr[r_id].shape)  {
					blocked <- true;
				}
			
				r_id <- r_id + 1;
			}
		
		}
	
		if !blocked  {
			do goto (target:target, on:people_graph[currentSimuState], speed:speed_walk_current);
		}else  {
			blocked_timer <- blocked_timer - step;
		}
		
	
		if blocked_timer < 0  {
			blocked_timer <- 3 * #minute;
			do goto (target:target, on:people_graph[currentSimuState], speed:speed_walk_current);
		}
	
	}else  {
		do goto (target:target, on:people_graph[currentSimuState], speed:speed_walk_current);
	}
	

	transition to: stroll_in_city when: not(to_exit) and wandering ;
	transition to: stroll_in_park when: ((not(to_exit) and not(wandering)) and not(to_culture)) and (location = target) ;
	transition to: queueing when: (not(to_exit) and to_culture) and (location = target) ;
	transition to: outside_sim when: to_exit and (location = target) ;
	exit  {
		walking <- false;
	}

}

in agents pedestrian465, Simulation 0
`````

**Comment by agrignard** [comment]
If it can help it's happenning with this seed
0.5370140012590653

Not sure where it comes from here is the error from Eclipse

``````
java.lang.NullPointerException
	at msi.gaml.operators.Spatial$Punctal.closest_points_with(Spatial.java:4155)
	at gaml.additions.GamlAdditions.lambda$431(GamlAdditions.java:488)
	at msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:77)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:75)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.statements.SetStatement.privateExecuteIn(SetStatement.java:150)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.IfStatement.privateExecuteIn(IfStatement.java:216)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.IfStatement.privateExecuteIn(IfStatement.java:216)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.IfStatement.privateExecuteIn(IfStatement.java:216)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.architecture.finite_state_machine.FsmStateStatement.beginExecution(FsmStateStatement.java:286)
	at msi.gaml.architecture.finite_state_machine.FsmStateStatement.privateExecuteIn(FsmStateStatement.java:320)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.architecture.finite_state_machine.FsmArchitecture.executeCurrentState(FsmArchitecture.java:127)
	at msi.gaml.architecture.finite_state_machine.FsmArchitecture.executeOn(FsmArchitecture.java:119)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:283)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:235)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:253)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:451)
	at msi.gama.runtime.concurrent.GamaExecutorService.doStep(GamaExecutorService.java:236)
	at msi.gama.runtime.concurrent.GamaExecutorService.step(GamaExecutorService.java:204)
	at msi.gama.metamodel.population.GamaPopulation.stepAgents(GamaPopulation.java:216)
	at msi.gama.metamodel.population.GamaPopulation.step(GamaPopulation.java:211)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:415)
	at msi.gama.metamodel.agent.GamlAgent.stepSubPopulations(GamlAgent.java:105)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:283)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:235)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:253)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:451)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:30)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$1(SimulationRunner.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Java error: nil value detected
	at msi.gama.runtime.exceptions.GamaRuntimeException.create(GamaRuntimeException.java:58)
	at msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:81)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:75)
	at msi.gaml.expressions.AbstractExpression.value(AbstractExpression.java:70)
	at msi.gaml.statements.SetStatement.privateExecuteIn(SetStatement.java:150)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.IfStatement.privateExecuteIn(IfStatement.java:216)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.IfStatement.privateExecuteIn(IfStatement.java:216)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.IfStatement.privateExecuteIn(IfStatement.java:216)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.statements.AbstractStatementSequence.privateExecuteIn(AbstractStatementSequence.java:56)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.architecture.finite_state_machine.FsmStateStatement.beginExecution(FsmStateStatement.java:286)
	at msi.gaml.architecture.finite_state_machine.FsmStateStatement.privateExecuteIn(FsmStateStatement.java:320)
	at msi.gaml.statements.AbstractStatement.executeOn(AbstractStatement.java:41)
	at msi.gaml.statements.AbstractStatementSequence.executeOn(AbstractStatementSequence.java:46)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.runtime.IScope.execute(IScope.java:506)
	at msi.gaml.architecture.finite_state_machine.FsmArchitecture.executeCurrentState(FsmArchitecture.java:127)
	at msi.gaml.architecture.finite_state_machine.FsmArchitecture.executeOn(FsmArchitecture.java:119)
	at msi.gama.runtime.ExecutionScope.execute(ExecutionScope.java:369)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:283)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:235)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:253)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:451)
	at msi.gama.runtime.concurrent.GamaExecutorService.doStep(GamaExecutorService.java:236)
	at msi.gama.runtime.concurrent.GamaExecutorService.step(GamaExecutorService.java:204)
	at msi.gama.metamodel.population.GamaPopulation.stepAgents(GamaPopulation.java:216)
	at msi.gama.metamodel.population.GamaPopulation.step(GamaPopulation.java:211)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:415)
	at msi.gama.metamodel.agent.GamlAgent.stepSubPopulations(GamlAgent.java:105)
	at msi.gama.metamodel.agent.AbstractAgent.doStep(AbstractAgent.java:283)
	at msi.gama.metamodel.agent.MinimalAgent.doStep(MinimalAgent.java:235)
	at msi.gama.metamodel.agent.AbstractAgent.step(AbstractAgent.java:253)
	at msi.gama.runtime.ExecutionScope.step(ExecutionScope.java:451)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$0(SimulationRunner.java:30)
	at msi.gama.runtime.concurrent.SimulationRunner.lambda$1(SimulationRunner.java:55)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at msi.gaml.operators.Spatial$Punctal.closest_points_with(Spatial.java:4155)
	at gaml.additions.GamlAdditions.lambda$431(GamlAdditions.java:488)
	at msi.gaml.expressions.BinaryOperator._value(BinaryOperator.java:77)
	... 71 more
`````

**Comment by ptaillandier** [comment]
I was not able to reproduce the issue...
However, the issue seems to come from the line: target <- closest_points_with(r,target_place)[0];
Could you check that target_place is not nil?
